event_sdl: Use 0 instead of NULL for int value
Fixes a build issue:

In file included from /usr/include/pthread.h:31,
                 from /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-musl/bits/gthr-default.h:35,
                 from /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/x86_64-gentoo-linux-musl/bits/gthr.h:148,
                 from /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/ext/atomicity.h:35,
                 from /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/bits/basic_string.h:39,
                 from /usr/lib/gcc/x86_64-gentoo-linux-musl/11.3.0/include/g++-v11/string:55,
                 from src/event.h:11,
                 from src/event_sdl.cpp:8:
src/event_sdl.cpp: In destructor 'TimedEventMgr::~TimedEventMgr()':
src/event_sdl.cpp:158:10: error: cannot convert 'std::nullptr_t' to 'int' in assignment
  158 |     id = NULL;
      |          ^~~~
src/event_sdl.cpp: In member function 'void TimedEventMgr::stop()':
src/event_sdl.cpp:194:14: error: cannot convert 'std::nullptr_t' to 'int' in assignment
  194 |         id = NULL;
      |              ^~~~
make: *** [<builtin>: src/event_sdl.o] Error 1